### PR TITLE
Move to monaco

### PR DESCRIPTION
**Pull request by basarat**
Thank your for visiting. Please :star: the project to keep the energy going :rose:

refs https://github.com/alm-tools/alm/issues/120

* [ ] Address all `TODO: mon` comments
* [x] Restore the styles for "find result" highlights
* [x] Rewrite find and replace
* [x] Rewire shared docs
* [x] Figure out the commonjs bundling story
* [x] Monokai color theme
* [x] Monokai background color
* [x] load editor config
* [x] TS syntax highlighting
* [x] Style the matching brackets as green like we did before
* [x] Rewire linter
* [x] Wire up linter
* [x] TSX syntax highlighting
* [x] Cursor jumps when a hidden editor comes back
* [x] Disable right click for now
* [x] Goto next error
* [x] Restore clipboard ring
* [x] Status bar should show version number
* [x] Git status
* [x] Rewire hover
* [x] see if whole document formatting is still slow (as we've had to disable edit batching)
* [x] Rewire autocomplete
* [x] Rewire git status (very important as this is our autosave)
* [x] delete `monacoRequire` if it wasn't needed (we should never need manual monacoRequire calls)
* [x] Instead of constantly bringing in more and more code figure out a way to put it into the monaco namespace
* [x] change the keyboard shortcut for formatting
* [x] Restore file outline
* [x] Git soft reset
* [x] Rewire jumpy
* [x] Jump tab still inserts an `enter`. Prevent that somehow
* [x] Duplicate line (should just trigger copy line up)
* [x] Wire up find and replace to use `word` selection automatically and move to state using if is in focus and find and replace was previously hidden
* [x] remove our goto line as the built in one is better ... tried wiring it up ... didn't work! :rose:
* [x] Restore TSX to TS
* [x] Restore find references with full modal
* [x] monaco css has stopped working
* [x] Restore goto defintion with full modal
* [x] Restore refactoring support in doccache
* [x] Restore rename with full modal
* [x] Monaco matching bracket shortcut conflicts with our tree view shortcut. Change it to ctrl+m (like sublime)
* [x] Restore showing the overrides information in the gutter
* [x] Style characters to match what we have for e.g. our omni search
* [x] The fold shortcut interferes with next / previous tab (tested on a mac)
* [x] monaco's f8 interferes with our "goto next error" but I like its "error display message" so find a compramise. Mod F8 is now for project wide. F8 is now for file only :heart:
* [x] Restore linting for tsconfig.json files
* [x] Rewire quickfix
* [x] Quick fix ... monaco also has its implementation `ctrl + .`. See if we can integrate (otherwise overwrite)
* [x] Register signature help!
* [x] Autocomplete signatures
* [x] Autocomplete path for imports
* [x] path completions should eat preceeding text
* [x] markdown syntax highlighting doesn't work
* [x] Autocomplete doesn't requery on prefix change :-/
* [x] Snippet support
* [x] Whatever is doing it for `.monaco-editor-hover.monaco-editor-background` is doing it wrong
* [x] Fix hover as its trimming too much

# Final

* [ ] Delete code mirror
  * [ ] linter
  * [ ] gitstatus
  * [ ] type info on hover + errors
  * [ ] jumpy
* [ ] TSX tag matching
* [ ] Consolidate all the debounce durations into `types`
* [ ] Move override information into an inline overlay
* [ ] F1 is wired to command palette (disable that for now)

### CODE REVIEW

**Comment by basarat** [comment]
I am at a point where I need to take a step back and review how the standalone editor is built up / published and automate it further. This would be similar to what we did with TypeScript (https://github.com/TypeStrong/ntypescript) as it saves us depending heavily on external publish cycles and API *visibility* decisions :rose:

**Comment by Alexisvt** [comment]
👍

**Comment by basarat** [comment]
This is ready! Scared to press that merge button though / publish. Definitely has *some* features missing (like tsconfig autocomplete / packa.json hover) but nothing major. Can I get a **yes please merge / release** from anyone?

**Comment by Alexisvt** [comment]
Wow do it!!!! 😍😍😍😍😘😆😆😆

**Comment by Alexisvt** [comment]
Yesssss i can't wait to be at home to test it 🙂🙂🙂👍👍👍

**Pull request merged**
