### PR TITLE
Rough implementation of themes

### PR DESCRIPTION
**Pull request by johnpaularthur**
Created themes folder under styles.  Moved most current css/typestyle from components into a theme folder called "alm".   Also created a new theme that roughly copies vscode.   Since es6 won't allow dynamic loading of paths based on variables, I'll have to find a better solution for switching.  To switch themes currently; delete "current", duplicate the theme folder you want and then rename to "current".  Might have to restart alm... even then sometimes alm holds on to the cached styles.

I'm a noob on most anything node, typescript & typestyle.  Won't be offended if this is rejected.

Default "current" theme is "alm".

alm theme:
image

vscode theme:
image

### CODE REVIEW

**Comment by basarat** [comment]
On man. I should add "features we are not targeting" to contributing. So sorry that you did this.

I want to provide something that works reliably across the board as advertised. I still need to be mindful of the amount of time we have available. With themes you get issues with certain things not looking right in certain cases. Don't want to handle that. If a feature is supported it *just works* with the default keybindings / default themes etc. 

Very limited customizability `=>` very little chance of it not working for you. Its like the macbook mindset :rose:

**Comment by basarat** [comment]
Added to contributing.md as I greatly value your time : https://github.com/alm-tools/alm/commit/4718f61e29f3a282b5aca4808ee3e0fa30a4d3b0 :rose:

**Comment by johnpaularthur** [comment]
No worries.   I saw someone was asking for customization and I too wanted to customize it.   I'm more interested in the core of what your doing with monaco and file operations.  I was starting to write my own electron app for a visual etl tool (with code behind editing).   I wanted to use monaco, but webpack (and/or electron) was not cooperating.   You've gotten further than I have so I hope you don't mind me using what you've accomplished so far to kick start my project.

**Comment by basarat** [comment]
> You've gotten further than I have so I hope you don't mind me using what you've accomplished so far to kick start my project.

100%. In fact nothing would make me happier. Tips on monaco setup: 

* setup `monaco-` in package.json 
* Serve up files from backend : https://github.com/alm-tools/alm/blob/2d8413f45930d4596cf38437a14b8b808376a147/src/server.ts#L37-L45
* Load up files in frontend : https://github.com/alm-tools/alm/blob/2d8413f45930d4596cf38437a14b8b808376a147/src/public/index.html#L94-L112

* Some experiments to work with monaco : https://github.com/alm-tools/alm/blob/1af2b0aa677fdfe69230d1f53092801d378258dd/src/typings/monaco.d.ts . You might not need `monacoRequire` if all your loading code is in index.html. I didn't need to use `monacoRequire` in the end either.

Hope it helps :rose:

**Pull request closed without merging**
